// <auto-generated />
using System;
using AccountService.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountService.API.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    [Migration("20260102095654_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountService.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Users_Status");

                    b.HasIndex("UserType")
                        .HasDatabaseName("IX_Users_UserType");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_Users_FullName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "123 Seller Street",
                            City = "New York",
                            Country = "USA",
                            CreatedAt = new DateTime(2025, 12, 3, 9, 56, 53, 744, DateTimeKind.Utc).AddTicks(7941),
                            Email = "john.seller@example.com",
                            FirstName = "John",
                            LastName = "Seller",
                            PhoneNumber = "555-0101",
                            State = "NY",
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 12, 3, 9, 56, 53, 744, DateTimeKind.Utc).AddTicks(7945),
                            UserType = 1,
                            ZipCode = "10001"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "456 Buyer Avenue",
                            City = "Los Angeles",
                            Country = "USA",
                            CreatedAt = new DateTime(2025, 12, 8, 9, 56, 53, 744, DateTimeKind.Utc).AddTicks(7950),
                            Email = "jane.buyer@example.com",
                            FirstName = "Jane",
                            LastName = "Buyer",
                            PhoneNumber = "555-0102",
                            State = "CA",
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 12, 8, 9, 56, 53, 744, DateTimeKind.Utc).AddTicks(7951),
                            UserType = 2,
                            ZipCode = "90001"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Address = "789 Carrier Road",
                            City = "Chicago",
                            Country = "USA",
                            CreatedAt = new DateTime(2025, 12, 13, 9, 56, 53, 744, DateTimeKind.Utc).AddTicks(7955),
                            Email = "mike.carrier@example.com",
                            FirstName = "Mike",
                            LastName = "Carrier",
                            PhoneNumber = "555-0103",
                            State = "IL",
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 12, 13, 9, 56, 53, 744, DateTimeKind.Utc).AddTicks(7955),
                            UserType = 3,
                            ZipCode = "60001"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Address = "321 Agent Plaza",
                            City = "Miami",
                            Country = "USA",
                            CreatedAt = new DateTime(2025, 12, 18, 9, 56, 53, 744, DateTimeKind.Utc).AddTicks(7959),
                            Email = "sarah.agent@example.com",
                            FirstName = "Sarah",
                            LastName = "Agent",
                            PhoneNumber = "555-0104",
                            State = "FL",
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 12, 18, 9, 56, 53, 744, DateTimeKind.Utc).AddTicks(7960),
                            UserType = 4,
                            ZipCode = "33101"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
