// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfferService.API.Data;

#nullable disable

namespace OfferService.API.Migrations
{
    [DbContext(typeof(OfferDbContext))]
    [Migration("20260102114604_SimplifiedOffers")]
    partial class SimplifiedOffers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OfferService.API.Models.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("OfferAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Offers_CreatedAt");

                    b.HasIndex("OfferAmount")
                        .HasDatabaseName("IX_Offers_OfferAmount");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("IX_Offers_SellerId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Offers_Status");

                    b.HasIndex("VIN")
                        .HasDatabaseName("IX_Offers_VIN");

                    b.HasIndex("Year")
                        .HasDatabaseName("IX_Offers_Year");

                    b.HasIndex("Make", "Model")
                        .HasDatabaseName("IX_Offers_Make_Model");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "123 Main Street, New York, NY 10001",
                            Condition = "Excellent",
                            CreatedAt = new DateTime(2025, 12, 28, 11, 46, 4, 165, DateTimeKind.Utc).AddTicks(5488),
                            Make = "Honda",
                            Model = "Civic",
                            OfferAmount = 25000.00m,
                            SellerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = 2,
                            UpdatedAt = new DateTime(2025, 12, 28, 11, 46, 4, 165, DateTimeKind.Utc).AddTicks(5491),
                            VIN = "1HGBH41JXMN109186",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "456 Oak Avenue, New York, NY 10002",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 12, 23, 11, 46, 4, 165, DateTimeKind.Utc).AddTicks(5498),
                            Make = "Toyota",
                            Model = "Camry",
                            OfferAmount = 28500.00m,
                            SellerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = 2,
                            UpdatedAt = new DateTime(2025, 12, 23, 11, 46, 4, 165, DateTimeKind.Utc).AddTicks(5498),
                            VIN = "2T1BURHE5JC123456",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("OfferService.API.Models.OfferImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("IX_OfferImages_DisplayOrder");

                    b.HasIndex("OfferId")
                        .HasDatabaseName("IX_OfferImages_OfferId");

                    b.ToTable("OfferImages");
                });

            modelBuilder.Entity("OfferService.API.Models.OfferImage", b =>
                {
                    b.HasOne("OfferService.API.Models.Offer", "Offer")
                        .WithMany("Images")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("OfferService.API.Models.Offer", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
